language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

install:
  - pip install git+git://github.com/udst/choicemodels.git
  - pip install .
  - pip install -r requirements-full.txt
  - pip install -r requirements-dev.txt
  - pip list
  - pip show urbansim_templates

script:
  - cd urbansim_templates/tests
  - coverage run -m pytest --verbose

after_success:
  - coverage report -m
  - coveralls