language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

install:
  - pip install git+git://github.com/udst/choicemodels.git
  - pip install .
  - pip list
  - pip show urbansim_templates

script:
  - cd urbansim_templates/tests
  - pytest *.py

after_success:
  - coverage report -m