language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

# Temporary solution for Python 3.7 until it's more cleanly supported
matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: true

install:
  - pip install git+git://github.com/udst/choicemodels.git
  - pip install .
  - pip install -r requirements-full.txt
  - pip install -r requirements-dev.txt
  - pip list
  - pip show urbansim_templates

script:
  - cd urbansim_templates/tests
  - coverage run --source urbansim_templates --module pytest --verbose

after_success:
  - coverage report --show-missing
  - coveralls